#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Reload the v4l2loopback module, it gets funny when used multiple times
sudo modprobe -r v4l2loopback
sudo modprobe v4l2loopback exclusive_caps=1 video_nr=13 card_label="ShareScreen"

TYPE="${1:-}"

if [[ "$TYPE" == "window" ]] || [[ -z "$TYPE" ]]; then
  REGION="$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -r)"
elif [[ "$TYPE" == "region" ]]; then
  REGION="$(slurp)"
fi

python3 \
  -m http.server \
  -d $SCRIPT_DIR/camera-share \
  65123 &

yes | wf-recorder \
  -g "$REGION" \
  --muxer=v4l2 \
  --codec=rawvideo \
  --file=/dev/video13 \
  --pixel-format=yuv420p \
  --force-yuv

kill -9 $(ps aux | grep python | grep http.server | tr -s ' ' | cut -d" " -f2)