#!/usr/bin/env bash
swaynag -t warning \
    -m 'Power Menu Options' \
    -b 'Logout' 'swaymsg exit' \
    -b 'Restart' 'shutdown -r now' \
    -b 'Shutdown'  'shutdown -h now' \
    --background='#22222266' \
    --button-background='#22222266' \
    --button-text='#FFD580' \
    --button-border-size=0 \
    --border-bottom='#FFD580' \
    --border-bottom-size=1 \
    --text='#FFD580'